cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/mnt/home/niprabhu/ntu-dsi-dcn/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/mnt/home/niprabhu/ntu-dsi-dcn/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Build.py", line 193, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 20438928: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-fno-strict-aliasing\', \'-fexceptions\', \'-fstack-protector\', \'-m64\', \'-mtune=generic\', \'-fPIC\', \'-fwrapv\', \'-fexceptions\', \'-fstack-protector\', \'-m64\', \'-mtune=generic\', \'-fPIC\', \'-fwrapv\', \'-fno-strict-aliasing\', \'-I/usr/include/python2.6\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DHAVE_IF_TUN_H=1\', \'-DPYTHONDIR="/usr/local/lib/python2.6/site-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib64/python2.6/site-packages"\', \'-D_GNU_SOURCE\', \'-DNDEBUG\', \'-D_GNU_SOURCE\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
